import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="bg-blue-100">
          <div className="flex flex-col h-[100vh]">
            {/* Top Navigation */}
            <div className="bg-slate-500">
              <ul className="flex text-white justify-around ">
                <li>Home</li>
                <li>Blog</li>
                <li>Post</li>
                <li>Contact us</li>
              </ul>
            </div>
            <div className="flex-1 bg-purple-400">
              <div className="flex h-[80vh]">
                {/* Side Navigation section */}
                <div className="bg-yellow-400 w-20 ">Side navigation</div>
                {/* Main Content section*/}
                <div className="bg-slate-300 flex-1 ">{children}</div>
              </div>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
